#!/bin/bash

echo "------------------------------"
echo "CLUSTER_NAME = ${CLUSTER_NAME:=cluster}"
echo "------------------------------"
echo

echo "delete k8s '$CLUSTER_NAME'? y/N"
read yn
if [ "$yn" != y ]; then
   echo "canceled"
   exit 0
fi

docker info > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "ERROR: Cannot connect docker"
    exit 1
fi

echo "deleting k8s using k3d"
k3d cluster delete $CLUSTER_NAME
echo "deleting docker network"
docker network rm $CLUSTER_NAME

